### PR TITLE
Stop buffering response on request abort. Fix #122

### LINKED ISSUE #122: Should asker stop buffering response on request abort?
In some cases `data` event can be fired after request abort. Asker continues buffering response (https://github.com/nodules/asker/blob/acc28e620c5cf1ef50b31bb470f8e94984a43bea/lib/asker.js#L539) until `error` or `end` event will be fired.

Should we fix it? I can change event handler like this
```js
res.on('data', function(chunk) {
    if (httpRequest.rejected) {
        // clear buffer
        // body = [];
        return;
    }

    body.push(chunk);
    bodyLength += chunk.length;
});
```

### PR DESCRIPTION
**Pull request by doochik**
These changes can't be tested unfortunately

### CODE REVIEW

**Comment by kaero** [comment]
@doochik add test, pls

**Comment by doochik** [comment]
I don't know how to test it because `body` is in private scope

**Comment by kaero** [comment]
ok, lgtm, because code is side covered by existing tests

**Comment by kaero** [comment]
`+ asker@1.0.5`

**Comment by narqo** [comment]
@kaero fill the changelog, please ;)

**Comment by kaero** [comment]
oh, s#!$

**Pull request merged**
